name: 'Rinde de Maíz en Argentina'

#forecast_date: 'now'
forecast_date: ['2014-11-01', '2014-12-01', '2015-01-01', '2015-02-01']

crop_type: 'MZ'
crop_template: 'MaizTardio.json'

configuration:
    # Format: days (int) | "HH:mm[:ss]" (string)
    frequency: 10 #'72:00:00'
    # Weather series type: combined or artificial.
    weather_series: 'combined'
    max_paralellism: 2


# OMM IDs of weather stations where simulations should be ran.        # Locations to be simulated. En el futuro, esto en vez de ser localidad, podría ser unidad cartográfica. En ese caso habría name de la unidad y coords del centroide
locations:                                # Name and coords of the location to be simulated and OMM ID of the weather station asociated to that location
    loc_1: {                                # FEB: Pondría location_1
        name: "Santa Paula",
        coord_x: '', # A completar únicamente el día que tengamos una base de datos de suelos.
        coord_y: '', # A completar únicamente el día que tengamos una base de datos de suelos.
        wth_station: 87548
    }

site_characteristics:                            # Estaba pensando que esto podía ser location_characteristics y que, al igual que DSSAT, se defina el/los suelos y estación meteorológica acá
    loc_1:
        soil_1: {
            id: "SBJUSB0001_1",                        # Soil id as it appears in the DSSAT soil file (ID_SOIL)
            series: "Santa Isabel",                    # Soil series
            prop: 0.5,                            # Proportion of area occupied by the soil in the location/cartografic unit to be simulated
            n_horizons: 9                        # Number of horizons of the soil
        }
        soil_2: {
            id: "SBJUSB0001_2",
            series: "Santa Magdalena",
            prop: 0.5,
            n_horizons: 8
        }

initial_conditions:
    loc_1:
        soil_1:
            frac_soil_water_all: # frac_full                # Fraction of soil water content in the whole soil profile at the starting of the simulation (fraction of the difference between SDUL and SLLL)
                low: 0.2
                mid: 0.5
                high: 0.8
            nh4_ppm_hrzn: [0.5, 0.5, 0.5, 0.5, 0.5, 0.2, 0.2, 0.2, 0.2] # ppm of NH4 in each soil horizon (SNH4)
            no3_ppm_hrzn: [0.5, 0.5, 0.5, 0.5, 0.5, 0.2, 0.2, 0.2, 0.2] # ppm of NO3 in each soil horizon (SNO3)
        soil_2:
            frac_soil_water_hrzn: # frac_ich20                # Fraction of soil water content in each soil horizon
                low: [0.5, 0.5, 0.5, 0.5, 0.5, 0.2, 0.2, 0.2]
                mid: [0.7, 0.7, 0.7, 0.7, 0.7, 0.5, 0.5, 0.5]
            nh4_ppm_hrzn: [0.5, 0.5, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
            no3_ppm_hrzn: [0.5, 0.5, 0.5, 0.5, 0.5, 0.2, 0.2, 0.2] # icno3


agronomic_management:
    loc_1:
        soil_1:
            mgmt_1: &id001 {
                mgmt_name: "High-tec management",
                start: 'S',
                irrig: 'A',
                sdday: 250,
                cultivar_id: "UAIC10",                               # Id of cultivar as it appears in the DSSAT genotype file (INGENO)
                planting_date: "yyyy0905", # date_1                  # Planting date (PDATE)
                plant_population: 6, # Buscar el mapeo (PPOP)        # Planting population at emergence(PPOE). Hay otras 3 variables pero no creo que convega incluirlas acá porque no varian casi nunca (PLDP, PLME y PLDS)
                n_fertilizer_dose: 70,                               # N in applied fertilizer (kg/ha) (FANM)
                n_fertilization_date: "yyyy0905"                     # N fertilization date (FDATE)
                # ACA HABRIA QUE DEFINIR SI VA O NO EL RIEGO COMO PARTE DEL MANEJO
            }
            mgmt_2: {
                sdday: 260,
                mgmt_name: "Low-tec management",
                cultivar_id: "UAIC10",
                planting_date: "yyyy0915"
            }
        soil_2:
            mgmt_1: {
                cultivar_id: "UAIC15",
                planting_date: "yyyy0905"
            }
            mgmt_2: *id001

results:
    cycle: ["PDAT", "HWAM"]
    daily: ["stress"]


# CONSULTAS
#- Donde se definen los detalles del inicio de simulación (START y SDATE)? (en principio creo que debe ser la misma para distintos manejos de un cultivo, no necesariamente para distintos cultivos)
## 1: Start: start (S por default?)
## 2: Inicio de simulación: sdday

#- El nombre de cada simulación se define automaticamente (SNAME)?
## Importa el nombre de la simulación?

#- Hay configuraciones que dependen dependen del cultivo (ej. el PHOTO de soja es "L" y el de maíz es "R"). Deberíamos definir eso acá, cuando se define un cultivo?
## Dos alternativas, o se deifne acá (EN CADA MANEJO) o se crea un experiment_template (JSON) por cada cultivo y se fija ahí.

#- Incluimos el riego en el management?
## Como les parezca más claro.