grid_resolution: 30 # Lat/lon grid resolution in arcminutes.
max_parallelism: 4

paths:
    psims: '/media/ramdisk/psims-schmidtfederico'
    # System general configuration file.
    temp_folder : ".tmp" # Should be a relative path, it'll be placed inside the root path.

    wth_grid_path: '.tmp/'
    rundir: './.tmp/rundir'

    # Directory for the weather DB to write CSV files with climate data.
    # If the database is running on the same node as the system, wth_csv_export == wth_csv_read.
    # Allows database to be at a remote server.
    wth_csv_export: "/home/usmfpts/Descargas/series_combinadas"
    # Mount point where database weather files can be read.
    wth_csv_read: "/home/federico/Desarrollo/PycharmProjects/PRinde/.tmp/wth"

weather_update_api:
#    url: 'http://crcssa.srsoft.com.ar/dbdump.php'
    url: 'http://qc.crc-sas.org/dbdump.php'
    user: 'crcssa_db_admin'
    # password: ''  # Uncomment to specify here, otherwise, it'll be looked up in the config/pwd directory.